version: "3"

services:
  app:
    image: wpafbo79/mini-cuda-with-prereqs:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
