version: "3"

services:
  app:
    image: wpafbo79/mini-cuda-with-prereqs:cuda-12.0.0_miniconda3-4.5.12_tini-0.19.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
