version: "3"

services:
  app:
    image: wpafbo79/real-esrgan:v20230211-010050
    restart: unless-stopped
    volumes:
      - experiments:/Real-ESRGAN/experiments/
      - inputs:/Real-ESRGAN/inputs/
      - results:/Real-ESRGAN/results/
      - weights:/Real-ESRGAN/weights/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  experiments:
    driver: local
  inputs:
    driver: local
  results:
    driver: local
  weights:
    driver: local
