version: "3"

services:
  app:
    image: wpafbo79/mini-cuda:
    restart: unless-stopped
    volumes:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
