version: "3"

services:
  app:
    image: wpafbo79/compvis-stable-diffusion:21f890f
    restart: unless-stopped
    volumes:
      - configs:/stable-diffusion/configs/
      - logs:/stable-diffusion/logs/
      - outputs:/stable-diffusion/outputs/
      - models-stable-diffusion:/stable-diffusion/models/ldm/stable-diffusion-v1/
      - training-data:/stable-diffusion/training-data/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  configs:
    driver: local
  logs:
    driver: local
  outputs:
    driver: local
  models-stable-diffusion:
    driver: local
  training-data:
    driver: local
