version: "3"

services:
  app:
    image: wpafbo79/invokeai:latest
    restart: unless-stopped
    volumes:
      - configs:/InvokeAI/configs/
      - logs:/InvokeAI/logs/
      - models:/InvokeAI/models/
      - outputs:/InvokeAI/outputs/
      - training-data:/InvokeAI/training-data/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  configs:
    driver: local
  logs:
    driver: local
  models:
    driver: local
  outputs:
    driver: local
  training-data:
    driver: local
