version: "3"

services:
  app:
    image: wpafbo79/invokeai:latest
    restart: unless-stopped
    volumes:
      - configs:/InvokeAI/configs/
      - embeddings:/InvokeAI/embeddings/
      - codeformer:/InvokeAI/models/codeformer/
      - models-gfpgan:/InvokeAI/models/gfpgan/
      - logs:/InvokeAI/logs/
      - outputs:/InvokeAI/outputs/
      - models-real-esrgan:/InvokeAI/models/realesrgan/
      - models-stable-diffusion:/InvokeAI/models/ldm/stable-diffusion-v1/
      - training-data:/InvokeAI/training-data/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  configs:
    driver: local
  embeddings:
    driver: local
  codeformer:
    driver: local
  models-gfpgan:
    driver: local
  logs:
    driver: local
  outputs:
    driver: local
  models-real-esrgan:
    driver: local
  models-stable-diffusion:
    driver: local
  training-data:
    driver: local
