version: "3"

services:
  app:
    image: wpafbo79/invokeai:v2.3.1.post2
    restart: unless-stopped
    volumes:
      - configs:/InvokeAI/configs/
      - models-diffusers:/InvokeAI/models/diffusers/
      - embeddings:/InvokeAI/embeddings/
      - models-codeformer:/InvokeAI/models/codeformer/
      - models-gfpgan:/InvokeAI/models/gfpgan/
      - logs:/InvokeAI/logs/
      - outputs:/InvokeAI/outputs/
      - models-real-esrgan:/InvokeAI/models/realesrgan/
      - models-stable-diffusion:/InvokeAI/models/ldm/stable-diffusion-v1/
      - training-data:/InvokeAI/training-data/
      - models-hub:/InvokeAI/models/hub/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  configs:
    driver: local
  models-diffusers:
    driver: local
  embeddings:
    driver: local
  models-codeformer:
    driver: local
  models-gfpgan:
    driver: local
  logs:
    driver: local
  outputs:
    driver: local
  models-real-esrgan:
    driver: local
  models-stable-diffusion:
    driver: local
  training-data:
    driver: local
  models-hub:
    driver: local
