version: "3"

services:
  app:
    image: wpafbo79/cuda-cudnn-with-prereqs-and-tensorrt:cuda-11.6.2-cudnn8_tini-0.19.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
