version: "3"

services:
  app:
    image: wpafbo79/gfpgan:latest
    restart: unless-stopped
    volumes:
      - experiments:/GFPGAN/experiments/
      - inputs:/GFPGAN/inputs/
      - results:/GFPGAN/results/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  experiments:
    driver: local
  inputs:
    driver: local
  results:
    driver: local
