version: "3"

services:
  app:
    image: wpafbo79/cuda-with-prereqs:cuda-12.0.0_tini-0.19.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
